version: '2'

services:
  
  apache:
    image: joaniznardo/ubuntum7http
    ##  hostname: webserver.lab40.edu
##  container_name: webserver.lab40.edu
    hostname: webserver
    container_name: webserver
    ports:      
      - '80:80'
      - '443:443'
    volumes:
##      - '/etc/localtime:/etc/localtime:ro'
        - './website01:/var/www/website01:ro'
    networks:
      x1:
        ipv4_address: 10.28.1.100

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.28.1.0/24
          ##        ip_range: 10.28.1.0/30
          gateway: 10.28.1.1
          aux_addresses:
            host1: 10.28.1.2
            host2: 10.28.1.3
