version: '2'

services:
  
  squid:
          #image: joaniznardo/ubuntum7base
    image: joaniznardo/ubuntum7proxy01
    hostname: squidhost
    container_name: squidcont 
    ##    cap_add:
    ##  - NET_ADMIN
    ##  - SYS_ADMIN
    ports:      
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './squid3:/etc/squid3:ro'
        #     - './sites-available:/etc/apache2/sites-available:ro'
    extra_hosts: &llistahosts
      - www.serverjoan.lab42:10.28.1.100        
      - www.elmeuprimerllocweb.org:10.28.1.100        
      - www.facebook.com:10.28.1.100        
      - www.apacheserver.test:10.28.1.100        
    networks:
      x1:
        ipv4_address: 10.28.1.90

  apache:
    image: joaniznardo/ubuntum7http
    hostname: webserver
    container_name: webserver
    ##    cap_add:
    ##  - NET_ADMIN
    ##  - SYS_ADMIN
    #    ports:      
    #  - '80:80'
    #  - '443:443'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './www:/var/www:ro'
      - './sites-available:/etc/apache2/sites-available:ro'
    networks:
      x1:
        ipv4_address: 10.28.1.100

  textclient:
    image: joaniznardo/ubuntum7base
    hostname: textclient
    container_name: textclient_cont
    domainname: lab42
    extra_hosts: *llistahosts
    networks:
      x1:
        ipv4_address: 10.28.1.99 

  firefox:
    image: jlesage/firefox
    hostname: firefox
    container_name: firefox
    environment:
      - FF_PREF_HTTP_PROXY=network.proxy.http=\10.28.1.90:3128\
      - HTTP_PROXY=10.28.1.90:3128
    extra_hosts: *llistahosts
    ports:
#novnc - web enabled remote desktop            
      - '5800:5800'
#vnc directe          
      - '5900:5900'

## config temporal
    volumes:
      - './firefox:/config:rw'
        #    tmpfs:
        #- '/config:rw'

    networks:
      x1:
        ipv4_address: 10.28.1.98 

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.28.1.0/24
          ##        ip_range: 10.28.1.0/30
          gateway: 10.28.1.1
          aux_addresses:
            host1: 10.28.1.2
            host2: 10.28.1.3
