version: '2'

services:
  
  apache:
    image: joaniznardo/ubuntum7http
    hostname: webserver
    container_name: webserver
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:      
      - '8080-8090:8080-8090'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './www:/var/www:ro'
      - './sites-available:/etc/apache2/sites-available:ro'
    networks:
      x1:
        ipv4_address: 10.28.1.100

  textclient:
    image: joaniznardo/ubuntum7base
    hostname: textclient
    container_name: textclient_cont
    domainname: lab42
    extra_hosts: &llistahosts
      - www.serverjoan.lab42:10.28.1.100
      - www.elmeuprimerllocweb.org:10.28.1.103        
      - www.facebook.com:10.28.1.102        
      - www.apacheserver.test:10.28.1.101       
    networks:
      x1:
        ipv4_address: 10.28.1.99 

  firefox:
    image: jlesage/firefox
    hostname: firefox
    container_name: firefox
    extra_hosts: *llistahosts
    ports:
#novnc - web enabled remote desktop            
      - '5800:5800'
#vnc directe          
      - '5900:5900'

## config temporal
##        volumes:
##            - '/docker/appdata/firefox:/config:rw'
    tmpfs:
      - '/config:rw'

    networks:
      x1:
        ipv4_address: 10.28.1.98 

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.28.1.0/24
          ##        ip_range: 10.28.1.0/30
          gateway: 10.28.1.1
          aux_addresses:
            host1: 10.28.1.2
            host2: 10.28.1.3
