version: '2'

services:
  
  tftpclient01:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: tftpclient01
    container_name: tftpclient01
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.28.1.101
    
  tftpserver:
    image: joaniznardo/ubuntum7tftp1
    privileged: true
    mem_limit: 100m
    hostname: tftpserver
    container_name: tftpserver
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.28.1.100

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/16
          ip_range: 10.28.1.0/30
          gateway: 10.28.1.1
          aux_addresses:
            host1: 10.28.1.2
            host2: 10.28.1.3
